### PR TITLE
Azc Module 3.0

### PR DESCRIPTION
**Pull request by dionytadema**
The module now uses a custom action to select a good location to build an azc. it takes water and other buildings into account and makes sure the azc is not to big.

**WARNING**, the custom action can take up to 3 minutes to calculate this area as we as municipality have a lot of land and this land is quite complex **EDIT** now the bot takes 20 seconds to calculate relevant areas instead of 3+ minutes

**TO RUN**, build the environment from PR https://github.com/eishub/tygron/pull/98 to run this bot

### CODE REVIEW

**Comment by levilime** [comment]
I think it's a really nice addition and a big improvement to https://github.com/levilime/ContextProject-Danshal/pull/67. I think also the parkmodule can benefit from this. I have additional thoughts though. One is that 3 minutes, or the time it took is way to long for the municipality not interacting with other stakeholders. It might be interesting to put this process in an other agent, because GOAL is a MAS system anyway and message the result back so that the Municipality can still do his job.

**Comment by dionytadema** [comment]
@levilime the logic is now slightly improved and the bot runs a lot better because we only look at one zone at a time, bringing the worst case back to 15-20 seconds without interaction. I don't see this as a big problem as it is not that long and happens only once or twice anyways, i think creating a separate bot for this is to much work

**Comment by levilime** [comment]
Yeah let's keep it in one agent for now, mostly because of issues with how we'd have to connect two Municipality agents to the same session.

**Comment by hmyeh** [comment]
Looks good :+1:

**Pull request merged**
