### PR TITLE
Update env 1.0.8

### PR DESCRIPTION
**Pull request by dionytadema**
tygron faalt versie 1.0.8. staat nog niet op de context branch

### CODE REVIEW

**Comment by levilime** [comment]
I agree, the mas agent now works with the current context branch on eishub/tygron, but please fix commit history first

**Comment by dionytadema** [comment]
commit history fixed

**Comment by levilime** [comment]
:+1:

**Comment by NickTUD** [comment]
The name of the map was not equal to the name of our own project. To avoid conflicts later, I changed the name to "contextvh". Besides that, your pr seems fine :+1:

**Pull request merged**
